### ISSUE TITLE
Issue compiling github page

### ISSUE THREAD

**Issue by Unitech** [keymetrics/doc-pm2#1]
![image](https://user-images.githubusercontent.com/757747/38434087-6bd4e7e6-39cd-11e8-89e4-f796e0a34a56.png)

**Comment by rendrap** [comment]
fixing #1 - tf liquid tag not recognized
---
**Why tf liquid tag not recognized**
Current project use [jekyll-multiple-languages-plugin](https://github.com/Anthony-Gaudino/jekyll-multiple-languages-plugin) to handle multi language feature.
It introduce `tf` tag to link between english and chinese .md document.
One of the caveat is, we can not use standard Jekyll way to host the project in gh-pages (This plugin is not natively supported by github-pages)

**The normal way of hosting Jekyll project is**
run `bundle exec jekyll build` in local dev, commit and push to the repo. Github-pages will generate _site folder **in the server** automatically. 
This generated _site folder is different from the one we have in local dev, in fact usually in development we exclude _site from git by putting it in .gitignore.
This can be done in master or gh-pages branch. github pages will host from _site folder.

**Workaround**
1. set jekyll to output to docs folder
2. set repo setting to serve from docs folder
