### ISSUE TITLE
Todos

### ISSUE THREAD

**Issue by Unitech** [keymetrics/doc-pm2#215]
- [ ] restore copy to clipboard
- [ ] Find a way to cache some file at nginx level ++ invalidation caching strategy
- [ ] jekyll seo: https://github.com/natfriedman/hello/commit/2cfa97d759f1e235c80fed2511c23d1ffd910db1#diff-aeb42283af8ef8e9da40ededd3ae2ab2R17
- [ ] contributor list at bottom of each page
- [x] fix anchor problems
- [x] hover on h1 does'nt make appear icon
- [x] anchor icon for h3 is blue instead of black

**Comment by robin-monnier** [comment]
jekyll seo ?

**Comment by robin-monnier** [comment]
Oh no, got it

**Comment by Unitech** [comment]
jekyll-seo-tag , it seems that it generates the seo meta tags for you, pretty useful

**Comment by robin-monnier** [comment]
i checked but it seems that many meta tags are missing (for example, they only support two tags for twitter).
SEO tags are already added on the head anyway.

**Comment by robin-monnier** [comment]
there are no anchors on h1
