### ISSUE TITLE
Unable to find deployment documentation.

### ISSUE THREAD

**Issue by Grayda** [keymetrics/doc-pm2#240]
The documentation for [deploying via SSH](https://pm2.io/doc/en/runtime/guide/easy-deploy-with-ssh/) tells me to consult the ecosystem file reference (which I assume is https://pm2.io/doc/en/runtime/reference/ecosystem-file/) for information about deployment options, but that page only seems to have options for defining apps, not for deployment.

Am I missing something here? If not, can the docs be updated?

**Comment by robin-monnier** [comment]
Hi,

Thanks for your message.

There was indeed a missing part. I've just updated the ecosystem file reference, there is now a section for the deployment options.

**Comment by Grayda** [comment]
Looking at the reference page, https://pm2.io/doc/en/runtime/reference/ecosystem-file/, I'm not able to see the change. Also I just browsed around on GitHub looking for any recently commits, but couldn't find any commits newer than 21 hours ago

Was the change made elsewhere, or does it go through another process before landing on GitHub / pm2.io?

**Comment by robin-monnier** [comment]
Deployment issue, now online !
