### ISSUE TITLE
Would I translate pm2 documentation in Korean?

### ISSUE THREAD

**Issue by trustyoo86** [keymetrics/doc-pm2#303]
Hello,
I'm node.js developer in Korea and used to pm2 plugins.
While looking through the documentation to use pm2 enterprise solution, I found translated page in China but not in Korean.

So, If allowed, I'll tranlate in Korean pm2 documentation pages.
Whould I translate this documentation in Korean? And Is there something the special rules?

Thank you.

**Comment by Unitech** [comment]
Hello @trustyoo86,
Sure feel free to translate the PM2 documentation in Korean. 
You can fork this repo: https://github.com/pm2-hive/pm2-hive.github.io and edit the content. Later I will see if I can make a multi language doc so we can have all markdown file within the same repo
Cheers

**Comment by trustyoo86** [comment]
Thank you for reply my issue :)
Would I translate doc-pm2 (this repository) too?
I want to translate pm2-hive and doc-pm2 repository in Korean.

Thank you :)

**Comment by Unitech** [comment]
Sure, feel free to fork doc-pm2/pm2-hive

**Comment by trustyoo86** [comment]
Okay If I translate page in Korean, I'll pull request this repository.
Thank you.
